// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDuWE9hLYIHvf9YnSWHInQScFrSK5Gaxw',
    appId: '1:373327506961:web:2baf9bd4d44c2fe2bdcbb0',
    messagingSenderId: '373327506961',
    projectId: 'smart-app-e97a4',
    authDomain: 'smart-app-e97a4.firebaseapp.com',
    storageBucket: 'smart-app-e97a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNkkjT-dfpcnReaxkshMIZof95BDV7FaE',
    appId: '1:373327506961:android:bdc1257a2fdafed5bdcbb0',
    messagingSenderId: '373327506961',
    projectId: 'smart-app-e97a4',
    storageBucket: 'smart-app-e97a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuTEPG25sIL6SzOK8DVg48Zi1GJ5OJMcA',
    appId: '1:373327506961:ios:b21f5399c99f7f12bdcbb0',
    messagingSenderId: '373327506961',
    projectId: 'smart-app-e97a4',
    storageBucket: 'smart-app-e97a4.firebasestorage.app',
    iosBundleId: 'com.baoudane.baoudaneApp',
  );
}
